version: '3'

services:

  dachs:
      container_name: dachs
      image: docker.io/gavodachs/dachs:latest
      tty: true
      network_mode: 'bridge'
      ports:
        - 8080:8080
      volumes:
        # persistent dachs log data
        - "${DACHS_LOGS_PATH:-../containers-storage/logs/dachs}:/var/gavo/logs"
        # # persistent postgres data
        # - ../docker-storage/postgres:
        - "${DACHS_POSTGRES_PATH:-../containers-storage/postgresql}:/var/lib/postgresql/data"
        # persistent RD data
        - "${DACHS_DATA_PATH:-../containers-input}:/var/gavo/inputs"

  awstats:
      container_name: awstats
      image: docker.io/gavodachs/awstats:latest
      depends_on:
        - dachs
      tty: true
      network_mode: 'bridge'
      ports:
        - 80:80
      volumese
        - "${DACHS_LOGS_PATH:-../containers-storage/logs/dachs}:/var/gavo/logs:ro"
