version: '3'

services:

  postgres:
    build:
      context: ./dachs
      args:
        PG_VERSION: "${PG_VERSION:-15}"
    image: dachs:postgres
    container_name: postgres
    tty: true
    network_mode: 'bridge'


  dachs:
    build:
      context: ./dachs
      dockerfile: Dockerfile.dachs_server
      args:
        INSTALL_REPO: "${INSTALL_REPO}"
        PG_VERSION: "${PG_VERSION:-15}"
    image: dachs:server
    container_name: dachs
    tty: true
    network_mode: 'bridge'
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - "${DACHS_LOGS_PATH:-./tmp/logs}:/var/gavo/logs"


  # awstats:
  #   container_name: awstats
  #   image: dachs:awstats
  #   depends_on:
  #     - dachs
  #   build:
  #     context: ./awstats
  #   tty: true
  #   network_mode: 'bridge'
  #   ports:
  #     - 80:80
  #   volumes:
  #     - "${DACHS_LOGS_PATH:-./tmp/logs}:/var/gavo/logs:ro"
